version: "3"

services:
  mysql:
    image: mysql/mysql-server:8.0.28
    container_name: mysql-playground
    environment:
      # https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html#docker_var_mysql-root-host
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1qazxsw2
      MYSQL_DATABASE: sakila
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "4306:3306"
